### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-seguramaria#1]
Muy buen trabajo @seguramaria!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 312 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [ ] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.container { display: flex }`, `.container { align-items: center }`
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by seguramaria** [comment]
@migueldelmazo 
Hola Miguel, creo que algunos de los fallos que me salen, yo los tengo bien.
 
-  _HTML > LINK: Debemos tener dos ficheros de estilos importados con un link._
En mi caso, yo tengo dos enlaces de estilos: Reset y Main. Y un tercer enlace de la fuente del texto.

-  _HTML > HEADER: La etiqueta img debe tener el atributo title._
En mi caso, tengo el title en el enlace:  
```
<a
            href="https://adalab.es/curso-desarrollo-web/"
            title="Ir a la página de Adalab"
            target="_blank"
          >
            <img src="./images/adalab-logo-155x61.png" alt="Logo de Adalab" />
          </a> 
```

- _HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS._
Yo he añadido a los lis del menú  `text-transform: uppercase;`

-  _HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS._
Lo mismo que lo anterior, tanto Contacto, como Blog, estaban dentro del listado del menú y les puse: `text-transform: uppercase;`

-  _HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS._
En la clase "main-title" apliqué la propiedad:  ` text-transform: capitalize;`

Ya me dices si estaría bien así o tendría que cambiar algo de esto. Los otros puntos sí que veo más claro que tendría que mejorarlos. Muchas gracias.

**Comment by migueldelmazo** [comment]
Hola @seguramaria te voy contestando:

> HTML > LINK: Debemos tener dos ficheros de estilos importados con un link.
En mi caso, yo tengo dos enlaces de estilos: Reset y Main. Y un tercer enlace de la fuente del texto.

Tienes razón, es fallo de autocorrecto.

> HTML > HEADER: La etiqueta img debe tener el atributo title.
En mi caso, tengo el title en el enlace:
```html
<a
            href="https://adalab.es/curso-desarrollo-web/"
            title="Ir a la página de Adalab"
            target="_blank"
          >
            <img src="./images/adalab-logo-155x61.png" alt="Logo de Adalab" />
</a> 
```

Tienes razón es fallo del autocorrector.

> HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
Yo he añadido a los lis del menú text-transform: uppercase;

El texto que tienes es **blog** y debe ser **Blog**. La primera en mayúscula. Piensa que contenido de tu página puede ser mostrado en algún sitio sin tus estilos, y por ello gramaticalmente debe estar bien.

Por ejemplo todo el texto que ves en la [página de Google](https://www.google.com/search?q=adalab&oq=adalab&aqs=chrome..69i57j0l3j69i60l4.2182j0j7&sourceid=chrome&ie=UTF-8) sobre Adalab es contenido de la página de Adalab, pero sin estilos.

> HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
Lo mismo que lo anterior, tanto Contacto, como Blog, estaban dentro del listado del menú y les puse: text-transform: uppercase;

Lo mismo que en el anterior :)

> HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
En la clase "main-title" apliqué la propiedad: text-transform: capitalize;

Lo mismo que en el anterior :)

Muy buen trabajo @seguramaria sigue así!!!

**Comment by migueldelmazo** [comment]
Por cierto dos cosillas:

1. Marca las casillas que hayas realizado.
1. Has hecho un README, es un detallito de calidad que se agradece mucho. Exquisito!!!
